<?php
namespace Mparaiso\SilexPress\Core\Form\Type;
use Mparaiso\SilexPress\Core\Form\DataTransformer\StringToHashdDataTransformer;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;

/**
 * Class MongoChoiceType
 * @package Mparaiso\SilexPress\Core\Form\Type
 * A list of documents from the database
 * the value is an ObjectId
 */
class HashType extends AbstractType
{


    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
        $builder->addModelTransformer(new StringToHashdDataTransformer());
    }

    function getParent()
    {
        return "text";
    }

    public function getName()
    {
        return "hash";
    }

}
